AllCops:
  TargetRubyVersion: 3.2.2
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Style/WordArray:
  Enabled: false
Metrics/BlockLength:
  Max: 25
  Exclude:
    - '**/*_spec.rb'